export const Category_Types = [
  {
    value: "pet_friendly",
    label: "Pet Friendly",
    icon: "paw",
    color: "#ff9422",
    details: "Activities and accommodations that welcome pets.",
  },
  {
    value: "outdoors",
    label: "Outdoor Recreation",
    icon: "leaf",
    color: "#51CF66",
    details: "Hiking, biking, and nature exploration activities.",
  },
  {
    value: "family_friendly",
    label: "Family Friendly",
    icon: "accessibility",
    color: "#e45fb5",
    details: "Activities suitable for all ages, including kids.",
  },
  {
    value: "popular_foods",
    label: "Popular Foods",
    icon: "restaurant",
    color: "#FF922B",
    details: "Must-try local dishes and food experiences.",
  },
  {
    value: "budget_travel",
    label: "Budget Travel",
    icon: "cash-outline",
    color: "#44935d",
    details: "Affordable activities and accommodations.",
  },
  {
    value: "cafe_sweets",
    label: "Cafe & Sweets",
    icon: "cafe",
    color: "#A0522D",
    details: "Cozy cafes and dessert spots.",
  },
  {
    value: "shopping",
    label: "Shopping",
    icon: "bag-handle",
    color: "#E64980",
    details: "Best shopping districts and unique boutiques.",
  },
  {
    value: "sightseeing",
    label: "Sightseeing",
    icon: "camera",
    color: "#4DABF7",
    details: "Iconic landmarks and must-see attractions.",
  },
  {
    value: "romantic",
    label: "Romantic",
    icon: "heart",
    color: "#ee4b61",
    details: "Perfect spots for couples and romantic experiences.",
  },
  {
    value: "business_trip",
    label: "Business Trip",
    icon: "briefcase",
    color: "#495057",
    details: "Efficient and convenient options for business travelers.",
  },
  {
    value: "adventure",
    label: "Adventure",
    icon: "compass",
    color: "#CC5DE8",
    details: "Thrilling outdoor and extreme activities.",
  },
  {
    value: "nightlife",
    label: "Nightlife",
    icon: "moon",
    color: "#5C7CFA",
    details: "Vibrant nightlife and entertainment options.",
  },
  {
    value: "relaxation",
    label: "Relaxation",
    icon: "flower",
    color: "#20C997",
    details: "Spa days and peaceful retreats.",
  },
];
