/**
 * Visual configuration for each `category_group` value from the places table.
 * Used for map markers, legend, popup headers, and search results.
 */

export interface POICONFIG {
  label: string;
  color: string;
  bgColor: string;
  icon: string;
}

export const poiCategoryList = [
  // food_and_drink
  "restaurant",
  "cafe",
  "bakery",
  "bar",
  "beer",
  "fast-food",
  "ice-cream",
  "teahouse",
  "drink_cup",
  "confectionery",
  "restaurant-noodle",
  "restaurant-sushi",
  "restaurant-pizza",
  "restaurant-seafood",
  "restaurant-bbq",
  "food",
  "school",
  "college",
  // accommodation
  "lodging",
  "campsite",
  "shelter",
  // tourism_and_attractions
  "attraction",
  "landmark",
  "monument",
  "historic",
  "castle",
  "place-of-worship",
  "religious-christian",
  "religious-muslim",
  "religious-jewish",
  "religious-buddhist",
  "religious-shinto",
  "observation-tower",
  "viewpoint",
  "lighthouse",
  "fountain",
  "amusement-park",
  "zoo",
  "aquarium",
  "garden",
  "rocket",
  // arts_and_culture
  "museum",
  "art-gallery",
  "theatre",
  "music",
  "cinema",
  "library",
  // parks_and_nature
  "park",
  "park-alt1",
  "natural",
  "farm",
  "beach",
  "water",
  "waterfall",
  "hot-spring",
  "volcano",
  "mountain",
  "playground",
  "dog-park",
  "picnic-site",
  "wetland",
  // structure_and_geography
  "bridge",
  "dam",
  "building",
  "islet_tree",
  "harbor",
  // shopping
  "shop",
  "grocery",
  "clothing-store",
  "jewelry-store",
  "gift",
  "furniture",
  "mobile-phone",
  "shoe",
  "gaming",
  "suitcase",
  // nightlife_and_entertainment
  "nightclub",
  "alcohol-shop",
  "karaoke",
  "casino",
  "bowling-alley",
  // sports_and_activities
  "gym",
  "fitness-centre",
  "swimming",
  "golf",
  "tennis",
  "skiing",
  "skateboard",
  "stadium",
  "soccer",
  "baseball",
  "basketball",
  // transit
  "triangle",
  "pedestrian",
  "cross_country_skiing",
  "climbing",
  "bus",
  "rail",
  "rail-metro",
  "rail-light",
  "ferry",
  "airport",
  "taxi",
  "car-rental",
  "bicycle",
  "bicycle-share",
  "car",
  "parking",
  "parking-garage",
  "heliport",
  // tranportation mode icons
  "pedestrian_t",
  "cross_country_skiing_t",
  "climbing_t",
  "bus_t",
  "rail_t",
  "rail-metro_t",
  "rail-light_t",
  "ferry_t",
  "airport_t",
  "taxi_t",
  "car-rental_t",
  "bicycle_t",
  "bicycle-share_t",
  "car_t",
  // public_and_civic
  "town-hall",
  "embassy",
  "post",
  "police",
  "fire-station",
  "hospital",
  "pharmacy",
  "information",
  "toilet",
  "marker",
  "cemetery",
  "sailing",
  // other
  "circle",
] as const;

export const POI_GROUPS: Record<string, POICONFIG> = {
  // ═══ Food & Drink ═══
  restaurant: {
    label: "Restaurant",
    color: "#fc7938",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  cafe: { label: "Cafe", color: "#C0392B", bgColor: "#FDEDEC", icon: "cafe" },
  coffee_shop: {
    label: "Coffee Shop",
    color: "#A93226",
    bgColor: "#FDEDEC",
    icon: "cafe",
  },
  bakery: {
    label: "Bakery",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "bakery",
  },
  bar: { label: "Bar", color: "#a436ff", bgColor: "#FDEDEC", icon: "bar" },
  pub: { label: "Pub", color: "#a436ff", bgColor: "#FDEDEC", icon: "beer" },
  fast_food_restaurant: {
    label: "Fast Food",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "fast-food",
  },
  food_court: {
    label: "Food Court",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "food",
  },
  ice_cream_shop: {
    label: "Ice Cream",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "ice-cream",
  },
  tea_room: {
    label: "Tea Room",
    color: "#A93226",
    bgColor: "#FDEDEC",
    icon: "teahouse",
  },
  juice_bar: {
    label: "Juice Bar",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "drink_cup",
  },
  dessert_shop: {
    label: "Dessert Shop",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "confectionery",
  },
  deli: { label: "Deli", color: "#E74C3C", bgColor: "#FDEDEC", icon: "food" },
  food_truck: {
    label: "Food Truck",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "fast-food",
  },
  brewery: {
    label: "Brewery",
    color: "#C0392B",
    bgColor: "#FDEDEC",
    icon: "beer",
  },
  winery: {
    label: "Winery",
    color: "#C0392B",
    bgColor: "#FDEDEC",
    icon: "alcohol-shop",
  },
  distillery: {
    label: "Distillery",
    color: "#C0392B",
    bgColor: "#FDEDEC",
    icon: "alcohol-shop",
  },
  tapas_restaurant: {
    label: "Tapas",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  ramen_restaurant: {
    label: "Ramen",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-noodle",
  },
  japanese_restaurant: {
    label: "Japanese",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-sushi",
  },
  italian_restaurant: {
    label: "Italian",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-pizza",
  },
  mexican_restaurant: {
    label: "Mexican",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  indian_restaurant: {
    label: "Indian",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  chinese_restaurant: {
    label: "Chinese",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-noodle",
  },
  thai_restaurant: {
    label: "Thai",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  french_restaurant: {
    label: "French",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  spanish_restaurant: {
    label: "Spanish",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  greek_restaurant: {
    label: "Greek",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  korean_restaurant: {
    label: "Korean",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  sushi_restaurant: {
    label: "Sushi",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-sushi",
  },
  pizza_restaurant: {
    label: "Pizza",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-pizza",
  },
  seafood_restaurant: {
    label: "Seafood",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-seafood",
  },
  steakhouse: {
    label: "Steakhouse",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-bbq",
  },
  vegetarian_restaurant: {
    label: "Vegetarian",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "restaurant",
  },
  noodle_house: {
    label: "Noodle House",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant-noodle",
  },
  breakfast_restaurant: {
    label: "Breakfast",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "cafe",
  },
  brunch_restaurant: {
    label: "Brunch",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "cafe",
  },
  buffet_restaurant: {
    label: "Buffet",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  street_food: {
    label: "Street Food",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "fast-food",
  },

  // ═══ Accommodation ═══
  hotel: {
    label: "Hotel",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  motel: {
    label: "Motel",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  hostel: {
    label: "Hostel",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  bed_and_breakfast: {
    label: "B&B",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  resort: {
    label: "Resort",
    color: "#2980B9",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  guest_house: {
    label: "Guest House",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  inn: { label: "Inn", color: "#3498DB", bgColor: "#EBF5FB", icon: "lodging" },
  vacation_rental: {
    label: "Vacation Rental",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  campground: {
    label: "Campground",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "campsite",
  },
  camping: {
    label: "Camping",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "campsite",
  },
  rv_park: {
    label: "RV Park",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "campsite",
  },
  lodge: {
    label: "Lodge",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  apartment_hotel: {
    label: "Apart-Hotel",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  boutique_hotel: {
    label: "Boutique Hotel",
    color: "#2980B9",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },

  // ═══ Tourism & Attractions ═══
  tourist_attraction: {
    label: "Attraction",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "attraction",
  },
  landmark: {
    label: "Landmark",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "landmark",
  },
  monument: {
    label: "Monument",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "monument",
  },
  memorial: {
    label: "Memorial",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "monument",
  },
  historic_site: {
    label: "Historic Site",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "historic",
  },
  castle: {
    label: "Castle",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "castle",
  },
  palace: {
    label: "Palace",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "castle",
  },
  ruins: {
    label: "Ruins",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "historic",
  },
  temple: {
    label: "Temple",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "place-of-worship",
  },
  shrine: {
    label: "Shrine",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "religious-shinto",
  },
  church: {
    label: "Church",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "religious-christian",
  },
  mosque: {
    label: "Mosque",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "religious-muslim",
  },
  synagogue: {
    label: "Synagogue",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "religious-jewish",
  },
  cathedral: {
    label: "Cathedral",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "religious-christian",
  },
  observation_deck: {
    label: "Observation Deck",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "observation-tower",
  },
  viewpoint: {
    label: "Viewpoint",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "viewpoint",
  },
  scenic_lookout: {
    label: "Scenic Lookout",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "viewpoint",
  },
  lighthouse: {
    label: "Lighthouse",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "lighthouse",
  },
  fountain: {
    label: "Fountain",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "fountain",
  },
  statue: {
    label: "Statue",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "monument",
  },
  clock_tower: {
    label: "Clock Tower",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "observation-tower",
  },
  arch: {
    label: "Arch",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "landmark",
  },
  theme_park: {
    label: "Theme Park",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "amusement-park",
  },
  amusement_park: {
    label: "Amusement Park",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "amusement-park",
  },
  water_park: {
    label: "Water Park",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "swimming",
  },
  zoo: { label: "Zoo", color: "#F39C12", bgColor: "#FEF9E7", icon: "zoo" },
  aquarium: {
    label: "Aquarium",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "aquarium",
  },
  botanical_garden: {
    label: "Botanical Garden",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "garden",
  },
  planetarium: {
    label: "Planetarium",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "rocket",
  },
  observation_wheel: {
    label: "Observation Wheel",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "attraction",
  },

  // ═══ Arts & Culture ═══
  museum: {
    label: "Museum",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  art_museum: {
    label: "Art Museum",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  art_gallery: {
    label: "Art Gallery",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "art-gallery",
  },
  history_museum: {
    label: "History Museum",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  science_museum: {
    label: "Science Museum",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  childrens_museum: {
    label: "Children's Museum",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  cultural_center: {
    label: "Cultural Center",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "art-gallery",
  },
  performing_arts_venue: {
    label: "Performing Arts",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "theatre",
  },
  theater: {
    label: "Theater",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "theatre",
  },
  opera_house: {
    label: "Opera House",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "theatre",
  },
  concert_hall: {
    label: "Concert Hall",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "music",
  },
  cinema: {
    label: "Cinema",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "cinema",
  },
  library: {
    label: "Library",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "library",
  },
  exhibition_center: {
    label: "Exhibition Center",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },

  // ═══ Parks & Nature ═══
  park: { label: "Park", color: "#27AE60", bgColor: "#EAFAF1", icon: "park" },
  national_park: {
    label: "National Park",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "park-alt1",
  },
  state_park: {
    label: "State Park",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "park-alt1",
  },
  garden: {
    label: "Garden",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "garden",
  },
  nature_reserve: {
    label: "Nature Reserve",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "natural",
  },
  nature_preserve: {
    label: "Nature Preserve",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "natural",
  },
  wildlife_sanctuary: {
    label: "Wildlife Sanctuary",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "natural",
  },
  forest: {
    label: "Forest",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "park-alt1",
  },
  trail: {
    label: "Trail",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "natural",
  },
  hiking_trail: {
    label: "Hiking Trail",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "natural",
  },
  beach: {
    label: "Beach",
    color: "#fcff45",
    bgColor: "#FEF9E7",
    icon: "beach",
  },
  lake: { label: "Lake", color: "#08a0ff", bgColor: "#EAFAF1", icon: "water" },
  river: {
    label: "River",
    color: "#08a0ff",
    bgColor: "#EAFAF1",
    icon: "water",
  },
  waterfall: {
    label: "Waterfall",
    color: "#08a0ff",
    bgColor: "#EAFAF1",
    icon: "waterfall",
  },
  hot_spring: {
    label: "Hot Spring",
    color: "#08a0ff",
    bgColor: "#EAFAF1",
    icon: "hot-spring",
  },
  volcano: {
    label: "Volcano",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "volcano",
  },
  cave: {
    label: "Cave",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "mountain",
  },
  canyon: {
    label: "Canyon",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "mountain",
  },
  playground: {
    label: "Playground",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "playground",
  },
  dog_park: {
    label: "Dog Park",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "dog-park",
  },
  recreation_area: {
    label: "Recreation Area",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "circle",
  },
  picnic_area: {
    label: "Picnic Area",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "picnic-site",
  },
  green_space: {
    label: "Green Space",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "wetland",
  },
  meadow: {
    label: "Meadow",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "wetland",
  },

  // ═══ Structure & Geography ═══
  bridge: {
    label: "Bridge",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "bridge",
  },
  canal: {
    label: "Canal",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "water",
  },
  dam: { label: "Dam", color: "#795548", bgColor: "#EFEBE9", icon: "dam" },
  desert: {
    label: "Desert",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "natural",
  },
  tower: {
    label: "Tower",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "observation-tower",
  },
  island: {
    label: "Island",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "islet_tree",
  },
  mountain: {
    label: "Mountain",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "mountain",
  },
  natural_hot_springs: {
    label: "Hot Springs",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "hot-spring",
  },
  pier: { label: "Pier", color: "#795548", bgColor: "#EFEBE9", icon: "harbor" },
  public_plaza: {
    label: "Public Plaza",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "building",
  },
  skyscraper: {
    label: "Skyscraper",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "building",
  },

  // ═══ Shopping ═══
  shopping_mall: {
    label: "Shopping Mall",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  shopping_center: {
    label: "Shopping Center",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  department_store: {
    label: "Department Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  market: {
    label: "Market",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "grocery",
  },
  farmers_market: {
    label: "Farmers Market",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "grocery",
  },
  flea_market: {
    label: "Flea Market",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  night_market: {
    label: "Night Market",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  souvenir_shop: {
    label: "Souvenir Shop",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "gift",
  },
  gift_shop: {
    label: "Gift Shop",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "gift",
  },
  bookstore: {
    label: "Bookstore",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "library",
  },
  clothing_store: {
    label: "Clothing Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "clothing-store",
  },
  boutique: {
    label: "Boutique",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "clothing-store",
  },
  jewelry_store: {
    label: "Jewelry Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "jewelry-store",
  },
  antique_shop: {
    label: "Antique Shop",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  art_shop: {
    label: "Art Shop",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "art-gallery",
  },
  convenience_store: {
    label: "Convenience Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "grocery",
  },
  supermarket: {
    label: "Supermarket",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "grocery",
  },
  grocery_store: {
    label: "Grocery Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "grocery",
  },
  outlet_store: {
    label: "Outlet Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  electronics_store: {
    label: "Electronics",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "mobile-phone",
  },
  toy_store: {
    label: "Toy Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "gaming",
  },
  music_store: {
    label: "Music Store",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "music",
  },
  sporting_goods_store: {
    label: "Sporting Goods",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "soccer",
  },

  // ═══ Nightlife & Entertainment ═══
  nightclub: {
    label: "Nightclub",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "nightclub",
  },
  lounge: {
    label: "Lounge",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "alcohol-shop",
  },
  karaoke: {
    label: "Karaoke",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "karaoke",
  },
  comedy_club: {
    label: "Comedy Club",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "theatre",
  },
  jazz_club: {
    label: "Jazz Club",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "music",
  },
  music_venue: {
    label: "Music Venue",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "music",
  },
  casino: {
    label: "Casino",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "casino",
  },
  bowling_alley: {
    label: "Bowling Alley",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "bowling-alley",
  },
  arcade: {
    label: "Arcade",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "gaming",
  },
  escape_room: {
    label: "Escape Room",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "attraction",
  },
  billiard_hall: {
    label: "Billiard Hall",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "gaming",
  },

  // ═══ Sports & Activities ═══
  gym: { label: "Gym", color: "#00BCD4", bgColor: "#E0F7FA", icon: "gym" },
  fitness_center: {
    label: "Fitness Center",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "fitness-centre",
  },
  yoga_studio: {
    label: "Yoga Studio",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "fitness-centre",
  },
  swimming_pool: {
    label: "Swimming Pool",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "swimming",
  },
  spa: {
    label: "Spa",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "hot-spring",
  },
  sauna: {
    label: "Sauna",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "hot-spring",
  },
  golf_course: {
    label: "Golf Course",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "golf",
  },
  tennis_court: {
    label: "Tennis Court",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "tennis",
  },
  ski_resort: {
    label: "Ski Resort",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "skiing",
  },
  surf_spot: {
    label: "Surf Spot",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "swimming",
  },
  diving_center: {
    label: "Diving Center",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "swimming",
  },
  climbing_gym: {
    label: "Climbing Gym",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "mountain",
  },
  skating_rink: {
    label: "Skating Rink",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "skateboard",
  },
  stadium: {
    label: "Stadium",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "stadium",
  },
  sports_complex: {
    label: "Sports Complex",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "stadium",
  },
  bike_rental: {
    label: "Bike Rental",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "bicycle",
  },
  boat_rental: {
    label: "Boat Rental",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "ferry",
  },
  kayak_rental: {
    label: "Kayak Rental",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "swimming",
  },

  // ═══ Transit ═══
  bus_station: {
    label: "Bus Station",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "bus",
  },
  bus_stop: {
    label: "Bus Stop",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "bus",
  },
  train_station: {
    label: "Train Station",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "rail",
  },
  subway_station: {
    label: "Subway Station",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "rail-metro",
  },
  metro_station: {
    label: "Metro Station",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "rail-metro",
  },
  tram_stop: {
    label: "Tram Stop",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "rail-light",
  },
  ferry_terminal: {
    label: "Ferry Terminal",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "ferry",
  },
  airport: {
    label: "Airport",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "airport",
  },
  airport_terminal: {
    label: "Airport Terminal",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "airport",
  },
  taxi_stand: {
    label: "Taxi Stand",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "taxi",
  },
  car_sharing: {
    label: "Car Sharing",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "car",
  },
  car_rental: {
    label: "Car Rental",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "car-rental",
  },
  bike_sharing: {
    label: "Bike Sharing",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "bicycle-share",
  },
  bike_sharing_station: {
    label: "Bike Share Station",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "bicycle-share",
  },
  parking_lot: {
    label: "Parking Lot",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "parking",
  },
  parking_garage: {
    label: "Parking Garage",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "parking-garage",
  },
  port: { label: "Port", color: "#729bb0", bgColor: "#ECEFF1", icon: "harbor" },
  cruise_terminal: {
    label: "Cruise Terminal",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "ferry",
  },
  heliport: {
    label: "Heliport",
    color: "#729bb0",
    bgColor: "#ECEFF1",
    icon: "heliport",
  },

  // ═══ Public & Civic ═══
  city_hall: {
    label: "City Hall",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
  town_hall: {
    label: "Town Hall",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
  government_office: {
    label: "Government Office",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
  embassy: {
    label: "Embassy",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "embassy",
  },
  consulate: {
    label: "Consulate",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "embassy",
  },
  post_office: {
    label: "Post Office",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "post",
  },
  police_station: {
    label: "Police Station",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "police",
  },
  fire_station: {
    label: "Fire Station",
    color: "#ff2d26",
    bgColor: "#EFEBE9",
    icon: "fire-station",
  },
  hospital: {
    label: "Hospital",
    color: "#ff2d26",
    bgColor: "#EFEBE9",
    icon: "hospital",
  },
  clinic: {
    label: "Clinic",
    color: "#ff2d26",
    bgColor: "#EFEBE9",
    icon: "hospital",
  },
  pharmacy: {
    label: "Pharmacy",
    color: "#ff2d26",
    bgColor: "#EFEBE9",
    icon: "pharmacy",
  },
  community_center: {
    label: "Community Center",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
  government: {
    label: "Government",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
  convention_center: {
    label: "Convention Center",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "building",
  },
  visitor_center: {
    label: "Visitor Center",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "information",
  },
  tourist_information: {
    label: "Tourist Info",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "information",
  },
  public_restroom: {
    label: "Public Restroom",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "toilet",
  },
  // education
  school: {
    label: "School",
    color: "#ffd000",
    bgColor: "#EFEBE9",
    icon: "school",
  },
  university: {
    label: "University",
    color: "#ffd000",
    bgColor: "#EFEBE9",
    icon: "college",
  },
  college: {
    label: "College",
    color: "#ffd000",
    bgColor: "#EFEBE9",
    icon: "college",
  },
  // park amenities
  basketball_court: {
    label: "Basketball Court",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "basketball",
  },
  soccer_field: {
    label: "Soccer Field",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "soccer",
  },
  baseball_field: {
    label: "Baseball Field",
    color: "#95A5A6",
    bgColor: "#EAFAF1",
    icon: "baseball",
  },
  pitch: {
    label: "Pitch",
    color: "#95A5A6",
    bgColor: "#EAFAF1",
    icon: "circle",
  },
  recreation_ground: {
    label: "Recreation Ground",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "circle",
  },
  cemetery: {
    label: "Cemetery",
    color: "#95A5A6",
    bgColor: "#EFEBE9",
    icon: "cemetery",
  },
  marina: {
    label: "Marina",
    color: "#0070ff",
    bgColor: "#EFEBE9",
    icon: "sailing",
  },
};

export const DEFAULT_CATEGORY: POICONFIG = {
  label: "Other",
  color: "#95A5A6",
  bgColor: "#F2F3F4",
  icon: "circle",
};

export function getPOIConfig(category: string | null | undefined): POICONFIG {
  if (!category) return DEFAULT_CATEGORY;
  return POI_GROUPS[category] ?? DEFAULT_CATEGORY;
}

// ─── Top-level category-group config (legend, search results) ───

export const CATEGORY_GROUP_CONFIG: Record<string, POICONFIG> = {
  food_and_drink: {
    label: "Food & Drink",
    color: "#E74C3C",
    bgColor: "#FDEDEC",
    icon: "restaurant",
  },
  accommodation: {
    label: "Accommodation",
    color: "#3498DB",
    bgColor: "#EBF5FB",
    icon: "lodging",
  },
  tourism_and_attractions: {
    label: "Tourism",
    color: "#F39C12",
    bgColor: "#FEF9E7",
    icon: "attraction",
  },
  arts_and_culture: {
    label: "Arts & Culture",
    color: "#9B59B6",
    bgColor: "#F4ECF7",
    icon: "museum",
  },
  parks_and_nature: {
    label: "Parks & Nature",
    color: "#27AE60",
    bgColor: "#EAFAF1",
    icon: "park-alt1",
  },
  structure_and_geography: {
    label: "Landmarks",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "bridge",
  },
  shopping: {
    label: "Shopping",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    icon: "shop",
  },
  nightlife_and_entertainment: {
    label: "Nightlife",
    color: "#FF6F00",
    bgColor: "#FFF3E0",
    icon: "nightclub",
  },
  sports_and_activities: {
    label: "Sports",
    color: "#00BCD4",
    bgColor: "#E0F7FA",
    icon: "soccer",
  },
  transit: {
    label: "Transit",
    color: "#607D8B",
    bgColor: "#ECEFF1",
    icon: "bus",
  },
  public_and_civic: {
    label: "Public & Civic",
    color: "#795548",
    bgColor: "#EFEBE9",
    icon: "town-hall",
  },
};

export function getCategoryGroupConfig(
  categoryGroup: string | null | undefined,
): POICONFIG {
  if (!categoryGroup) return DEFAULT_CATEGORY;
  return CATEGORY_GROUP_CONFIG[categoryGroup] ?? DEFAULT_CATEGORY;
}

export const ALL_CATEGORY_GROUPS = Object.keys(CATEGORY_GROUP_CONFIG);
